/**
 * This class is generated by jOOQ
 */
package tech.codingclub.helix.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SongRecord extends org.jooq.impl.TableRecordImpl<tech.codingclub.helix.tables.records.SongRecord> implements org.jooq.Record11<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 402374765;

	/**
	 * Setter for <code>public.song.song_name</code>.
	 */
	public void setSongName(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.song.song_name</code>.
	 */
	public java.lang.String getSongName() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>public.song.parent_link</code>.
	 */
	public void setParentLink(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.song.parent_link</code>.
	 */
	public java.lang.String getParentLink() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.song.link</code>.
	 */
	public void setLink(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.song.link</code>.
	 */
	public java.lang.String getLink() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>public.song.album</code>.
	 */
	public void setAlbum(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.song.album</code>.
	 */
	public java.lang.String getAlbum() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>public.song.duration</code>.
	 */
	public void setDuration(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.song.duration</code>.
	 */
	public java.lang.String getDuration() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>public.song.singers</code>.
	 */
	public void setSingers(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.song.singers</code>.
	 */
	public java.lang.String getSingers() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>public.song.lyricist</code>.
	 */
	public void setLyricist(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.song.lyricist</code>.
	 */
	public java.lang.String getLyricist() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>public.song.music_director</code>.
	 */
	public void setMusicDirector(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>public.song.music_director</code>.
	 */
	public java.lang.String getMusicDirector() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>public.song.download_128</code>.
	 */
	public void setDownload_128(java.lang.String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>public.song.download_128</code>.
	 */
	public java.lang.String getDownload_128() {
		return (java.lang.String) getValue(8);
	}

	/**
	 * Setter for <code>public.song.download_320</code>.
	 */
	public void setDownload_320(java.lang.String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>public.song.download_320</code>.
	 */
	public java.lang.String getDownload_320() {
		return (java.lang.String) getValue(9);
	}

	/**
	 * Setter for <code>public.song.image_url</code>.
	 */
	public void setImageUrl(java.lang.String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>public.song.image_url</code>.
	 */
	public java.lang.String getImageUrl() {
		return (java.lang.String) getValue(10);
	}

	// -------------------------------------------------------------------------
	// Record11 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row11<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row11) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row11<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row11) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return tech.codingclub.helix.tables.Song.SONG.SONG_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return tech.codingclub.helix.tables.Song.SONG.PARENT_LINK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return tech.codingclub.helix.tables.Song.SONG.LINK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return tech.codingclub.helix.tables.Song.SONG.ALBUM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return tech.codingclub.helix.tables.Song.SONG.DURATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return tech.codingclub.helix.tables.Song.SONG.SINGERS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return tech.codingclub.helix.tables.Song.SONG.LYRICIST;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return tech.codingclub.helix.tables.Song.SONG.MUSIC_DIRECTOR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field9() {
		return tech.codingclub.helix.tables.Song.SONG.DOWNLOAD_128;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field10() {
		return tech.codingclub.helix.tables.Song.SONG.DOWNLOAD_320;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field11() {
		return tech.codingclub.helix.tables.Song.SONG.IMAGE_URL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getSongName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getParentLink();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getLink();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getAlbum();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getDuration();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getSingers();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getLyricist();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getMusicDirector();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value9() {
		return getDownload_128();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value10() {
		return getDownload_320();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value11() {
		return getImageUrl();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SongRecord value1(java.lang.String value) {
		setSongName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SongRecord value2(java.lang.String value) {
		setParentLink(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SongRecord value3(java.lang.String value) {
		setLink(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SongRecord value4(java.lang.String value) {
		setAlbum(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SongRecord value5(java.lang.String value) {
		setDuration(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SongRecord value6(java.lang.String value) {
		setSingers(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SongRecord value7(java.lang.String value) {
		setLyricist(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SongRecord value8(java.lang.String value) {
		setMusicDirector(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SongRecord value9(java.lang.String value) {
		setDownload_128(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SongRecord value10(java.lang.String value) {
		setDownload_320(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SongRecord value11(java.lang.String value) {
		setImageUrl(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SongRecord values(java.lang.String value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.String value5, java.lang.String value6, java.lang.String value7, java.lang.String value8, java.lang.String value9, java.lang.String value10, java.lang.String value11) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SongRecord
	 */
	public SongRecord() {
		super(tech.codingclub.helix.tables.Song.SONG);
	}

	/**
	 * Create a detached, initialised SongRecord
	 */
	public SongRecord(java.lang.String songName, java.lang.String parentLink, java.lang.String link, java.lang.String album, java.lang.String duration, java.lang.String singers, java.lang.String lyricist, java.lang.String musicDirector, java.lang.String download_128, java.lang.String download_320, java.lang.String imageUrl) {
		super(tech.codingclub.helix.tables.Song.SONG);

		setValue(0, songName);
		setValue(1, parentLink);
		setValue(2, link);
		setValue(3, album);
		setValue(4, duration);
		setValue(5, singers);
		setValue(6, lyricist);
		setValue(7, musicDirector);
		setValue(8, download_128);
		setValue(9, download_320);
		setValue(10, imageUrl);
	}
}
