/**
 * This class is generated by jOOQ
 */
package tech.codingclub.helix.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Cart extends org.jooq.impl.TableImpl<tech.codingclub.helix.tables.records.CartRecord> {

	private static final long serialVersionUID = 903963047;

	/**
	 * The singleton instance of <code>public.cart</code>
	 */
	public static final tech.codingclub.helix.tables.Cart CART = new tech.codingclub.helix.tables.Cart();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<tech.codingclub.helix.tables.records.CartRecord> getRecordType() {
		return tech.codingclub.helix.tables.records.CartRecord.class;
	}

	/**
	 * The column <code>public.cart.user_id</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.CartRecord, java.lang.Long> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>public.cart.product_id</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.CartRecord, java.lang.Long> PRODUCT_ID = createField("product_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * Create a <code>public.cart</code> table reference
	 */
	public Cart() {
		this("cart", null);
	}

	/**
	 * Create an aliased <code>public.cart</code> table reference
	 */
	public Cart(java.lang.String alias) {
		this(alias, tech.codingclub.helix.tables.Cart.CART);
	}

	private Cart(java.lang.String alias, org.jooq.Table<tech.codingclub.helix.tables.records.CartRecord> aliased) {
		this(alias, aliased, null);
	}

	private Cart(java.lang.String alias, org.jooq.Table<tech.codingclub.helix.tables.records.CartRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, tech.codingclub.helix.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<tech.codingclub.helix.tables.records.CartRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<tech.codingclub.helix.tables.records.CartRecord>>asList(tech.codingclub.helix.Keys.CART_USER_ID_PRODUCT_ID_KEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<tech.codingclub.helix.tables.records.CartRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<tech.codingclub.helix.tables.records.CartRecord, ?>>asList(tech.codingclub.helix.Keys.CART__USER_ID, tech.codingclub.helix.Keys.CART__PRODUCT_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public tech.codingclub.helix.tables.Cart as(java.lang.String alias) {
		return new tech.codingclub.helix.tables.Cart(alias, this);
	}

	/**
	 * Rename this table
	 */
	public tech.codingclub.helix.tables.Cart rename(java.lang.String name) {
		return new tech.codingclub.helix.tables.Cart(name, null);
	}
}
