/**
 * This class is generated by jOOQ
 */
package tech.codingclub.helix.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Customer extends org.jooq.impl.TableImpl<tech.codingclub.helix.tables.records.CustomerRecord> {

	private static final long serialVersionUID = 949790011;

	/**
	 * The singleton instance of <code>public.customer</code>
	 */
	public static final tech.codingclub.helix.tables.Customer CUSTOMER = new tech.codingclub.helix.tables.Customer();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<tech.codingclub.helix.tables.records.CustomerRecord> getRecordType() {
		return tech.codingclub.helix.tables.records.CustomerRecord.class;
	}

	/**
	 * The column <code>public.customer.name</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.CustomerRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>public.customer.email</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.CustomerRecord, java.lang.String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>public.customer.password</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.CustomerRecord, java.lang.String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

	/**
	 * The column <code>public.customer.token</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.CustomerRecord, java.lang.String> TOKEN = createField("token", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>public.customer.id</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.CustomerRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>public.customer</code> table reference
	 */
	public Customer() {
		this("customer", null);
	}

	/**
	 * Create an aliased <code>public.customer</code> table reference
	 */
	public Customer(java.lang.String alias) {
		this(alias, tech.codingclub.helix.tables.Customer.CUSTOMER);
	}

	private Customer(java.lang.String alias, org.jooq.Table<tech.codingclub.helix.tables.records.CustomerRecord> aliased) {
		this(alias, aliased, null);
	}

	private Customer(java.lang.String alias, org.jooq.Table<tech.codingclub.helix.tables.records.CustomerRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, tech.codingclub.helix.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<tech.codingclub.helix.tables.records.CustomerRecord, java.lang.Long> getIdentity() {
		return tech.codingclub.helix.Keys.IDENTITY_CUSTOMER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<tech.codingclub.helix.tables.records.CustomerRecord> getPrimaryKey() {
		return tech.codingclub.helix.Keys.CUSTOMER_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<tech.codingclub.helix.tables.records.CustomerRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<tech.codingclub.helix.tables.records.CustomerRecord>>asList(tech.codingclub.helix.Keys.CUSTOMER_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public tech.codingclub.helix.tables.Customer as(java.lang.String alias) {
		return new tech.codingclub.helix.tables.Customer(alias, this);
	}

	/**
	 * Rename this table
	 */
	public tech.codingclub.helix.tables.Customer rename(java.lang.String name) {
		return new tech.codingclub.helix.tables.Customer(name, null);
	}
}
