/**
 * This class is generated by jOOQ
 */
package tech.codingclub.helix.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Product extends org.jooq.impl.TableImpl<tech.codingclub.helix.tables.records.ProductRecord> {

	private static final long serialVersionUID = 1777722583;

	/**
	 * The singleton instance of <code>public.product</code>
	 */
	public static final tech.codingclub.helix.tables.Product PRODUCT = new tech.codingclub.helix.tables.Product();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<tech.codingclub.helix.tables.records.ProductRecord> getRecordType() {
		return tech.codingclub.helix.tables.records.ProductRecord.class;
	}

	/**
	 * The column <code>public.product.id</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.ProductRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.product.product_name</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.ProductRecord, java.lang.String> PRODUCT_NAME = createField("product_name", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>public.product.price</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.ProductRecord, java.lang.Long> PRICE = createField("price", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>public.product.image_link</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.ProductRecord, java.lang.String> IMAGE_LINK = createField("image_link", org.jooq.impl.SQLDataType.VARCHAR.length(300), this, "");

	/**
	 * Create a <code>public.product</code> table reference
	 */
	public Product() {
		this("product", null);
	}

	/**
	 * Create an aliased <code>public.product</code> table reference
	 */
	public Product(java.lang.String alias) {
		this(alias, tech.codingclub.helix.tables.Product.PRODUCT);
	}

	private Product(java.lang.String alias, org.jooq.Table<tech.codingclub.helix.tables.records.ProductRecord> aliased) {
		this(alias, aliased, null);
	}

	private Product(java.lang.String alias, org.jooq.Table<tech.codingclub.helix.tables.records.ProductRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, tech.codingclub.helix.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<tech.codingclub.helix.tables.records.ProductRecord, java.lang.Long> getIdentity() {
		return tech.codingclub.helix.Keys.IDENTITY_PRODUCT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<tech.codingclub.helix.tables.records.ProductRecord> getPrimaryKey() {
		return tech.codingclub.helix.Keys.PRODUCT_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<tech.codingclub.helix.tables.records.ProductRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<tech.codingclub.helix.tables.records.ProductRecord>>asList(tech.codingclub.helix.Keys.PRODUCT_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public tech.codingclub.helix.tables.Product as(java.lang.String alias) {
		return new tech.codingclub.helix.tables.Product(alias, this);
	}

	/**
	 * Rename this table
	 */
	public tech.codingclub.helix.tables.Product rename(java.lang.String name) {
		return new tech.codingclub.helix.tables.Product(name, null);
	}
}
