/**
 * This class is generated by jOOQ
 */
package tech.codingclub.helix.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Song extends org.jooq.impl.TableImpl<tech.codingclub.helix.tables.records.SongRecord> {

	private static final long serialVersionUID = -1097952049;

	/**
	 * The singleton instance of <code>public.song</code>
	 */
	public static final tech.codingclub.helix.tables.Song SONG = new tech.codingclub.helix.tables.Song();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<tech.codingclub.helix.tables.records.SongRecord> getRecordType() {
		return tech.codingclub.helix.tables.records.SongRecord.class;
	}

	/**
	 * The column <code>public.song.song_name</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.SongRecord, java.lang.String> SONG_NAME = createField("song_name", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>public.song.parent_link</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.SongRecord, java.lang.String> PARENT_LINK = createField("parent_link", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>public.song.link</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.SongRecord, java.lang.String> LINK = createField("link", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>public.song.album</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.SongRecord, java.lang.String> ALBUM = createField("album", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>public.song.duration</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.SongRecord, java.lang.String> DURATION = createField("duration", org.jooq.impl.SQLDataType.VARCHAR.length(10), this, "");

	/**
	 * The column <code>public.song.singers</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.SongRecord, java.lang.String> SINGERS = createField("singers", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>public.song.lyricist</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.SongRecord, java.lang.String> LYRICIST = createField("lyricist", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>public.song.music_director</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.SongRecord, java.lang.String> MUSIC_DIRECTOR = createField("music_director", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>public.song.download_128</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.SongRecord, java.lang.String> DOWNLOAD_128 = createField("download_128", org.jooq.impl.SQLDataType.VARCHAR.length(200), this, "");

	/**
	 * The column <code>public.song.download_320</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.SongRecord, java.lang.String> DOWNLOAD_320 = createField("download_320", org.jooq.impl.SQLDataType.VARCHAR.length(200), this, "");

	/**
	 * The column <code>public.song.image_url</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.SongRecord, java.lang.String> IMAGE_URL = createField("image_url", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * Create a <code>public.song</code> table reference
	 */
	public Song() {
		this("song", null);
	}

	/**
	 * Create an aliased <code>public.song</code> table reference
	 */
	public Song(java.lang.String alias) {
		this(alias, tech.codingclub.helix.tables.Song.SONG);
	}

	private Song(java.lang.String alias, org.jooq.Table<tech.codingclub.helix.tables.records.SongRecord> aliased) {
		this(alias, aliased, null);
	}

	private Song(java.lang.String alias, org.jooq.Table<tech.codingclub.helix.tables.records.SongRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, tech.codingclub.helix.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public tech.codingclub.helix.tables.Song as(java.lang.String alias) {
		return new tech.codingclub.helix.tables.Song(alias, this);
	}

	/**
	 * Rename this table
	 */
	public tech.codingclub.helix.tables.Song rename(java.lang.String name) {
		return new tech.codingclub.helix.tables.Song(name, null);
	}
}
